### ISSUE TITLE
Getting errors

### ISSUE THREAD

**Issue by shujaatak** [dridk/QFontIcon#3]
I am using the same file which is included with QFontIcon project.

`DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Fixedsys", pointsize=9.75, pixelsize=15, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-15) dpi=96`

**Comment by dridk** [comment]
Is the example working? Which Qt version are you using? Which os ? Thanks for your feedback

**Comment by shujaatak** [comment]
I am using Qt5.12.1 MSVC 2015 64bit on Windows 10. The example is not working properly, some icons are displayed correctly but some are not. I get the above error when running the example provided with this QFontIcon project.
